---
# Set update schedule for GitHub Actions

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    labels:
      - "github_actions"
      - "chore"
  # Maintain dependencies for Devcontainer dependencies
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "chore"
